name: Crypto S&R Scanner 247

on:
  schedule:
    - cron: '0 */6 * * *'  # Runs automatically every 6 hours
  workflow_dispatch:      # Allows you to run it manually with a click

jobs:
  run-scanner:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Scanner Script
        run: python main.py
